Code Reviewer Project Milestone
MasumaJaffery/Code-Reviewer-Project pull request #1
Opened 2023-04-03 15:56 UTC by MasumaJaffery

In this Milestone:
1. Add Linters.
2. Add HTML & CSS Files.
3. Styling Forn with proper semantics.
Thanks for taking the time and review my PR.

2023-04-03 18:12 UTC, MasumaJaffery reviewed
Hello @MasumaJaffery!
# **Changes Required** ♻️
Kindly check the inline comments for review. 
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋
**Highlights** 🌟
✔️ PR Descriptions
✔️ Linters checks are passing
✔️ Readme is professional.
Please take a look at my comments to make improvements and Submit for a re-review when you correct errors and add changes, and if you have any concerns or questions, let me know.
Cheers and Happy coding!👏👏👏

2023-04-03 18:38 UTC, divinecharlotte requested changes
Hi @MasumaJaffery        , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 


- Descriptive PR ✔️
- linters are passing 👍  
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._



## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 18:38 UTC, divinecharlotte commented on .github/workflows/linters.yml
- [ ] kindly consider phrasing your comments politely as suggestions instead of orders.
For example:

```
* This is a polite suggestion: *"I think it would be better to use semantic tags"*
* This reads as an order: *"Use semantic tags"*
```

to make your review kind 

- [ ] kindly consider also including the reason `why`for changes  to make the student understand well why the above change

2023-04-03 18:38 UTC, divinecharlotte commented on style.css
> +  box-sizing: border-box;
- [ ] kindly consider phrasing your comments politely as suggestions instead of orders.
For example:

```
* This is a polite suggestion: *"I think it would be better to use semantic tags"*
* This reads as an order: *"Use semantic tags"*
```

to make your review kind 

- [ ] and also consider making your  comments clear and easy to understand for the student 
here is an example: 
```
* This is a clear comment: *The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?*
* This is a vague comment: *The README is not descriptive, why don't you make it better?*
```

2023-04-03 18:38 UTC, divinecharlotte commented on style.css
> +  border-radius: 4px;
- [ ] kindly consider phrasing your comments politely as suggestions instead of orders.
For example:

```
* This is a polite suggestion: *"I think it would be better to use semantic tags"*
* This reads as an order: *"Use semantic tags"*
```

to make your review kind 

- [ ] and also consider making your  comments clear and easy to understand for the student 
here is an example: 
```
* This is a clear comment: *The README's "Built With" and "Getting Started" sections are currently empty. Why don't you add content, listing the technology used in the project and how to run it, to them so your README is more informative and professional?*
* This is a vague comment: *The README is not descriptive, why don't you make it better?*

2023-04-04 11:37 UTC, MasumaJaffery reviewed
Hello Masuma!
Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
**Highlights**
✅ Good commit history 👌
✅ Linters test passed 💯
✅ Html and CSS semantics is good 👏 👏
✅ Github flows are good 👍 👍
**Required Changes** ♻️ 
There are still very few things you need to fix, as in the comments below.
Cheers and Happy coding!👏👏👏

2023-04-04 11:37 UTC, MasumaJaffery commented on style.css
> +  border-radius: 4px;
Kindly use id or class if you used it in your form tag! Because id and class that we used in HTML tags have a great impact, if we use them in CSS.

2023-04-04 11:37 UTC, MasumaJaffery commented on index.html
> -
Kindly, I suggest you do not use white spaces in the code.

2023-04-04 11:42 UTC, binhussen commented on style.css
> +  border-radius: 4px;
- [Optional ] Kindle use a couple of emojis and/or gifs in the review, they make the code review more human-friendly 👽🤖.

2023-04-04 11:45 UTC, binhussen commented on index.html
> -
- Kindly, always includes an explanation, a "why", for each requested change. as the previous reviewer suggested you 👌
- [Optional ] Kindle use a couple of emojis and/or gifs in the review, they make the code review more human-friendly 👽🤖.

2023-04-04 11:48 UTC, binhussen requested changes
Hi @MasumaJaffery , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


 ## Required Changes ♻️
_Check the comments under your review._

## Optional suggestions
- [Optional] Kindly, don’t write a new review again, instead, edit the comment that the reviewer suggested and submit it for the next review 👍

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 14:30 UTC, MasumaJaffery commented on style.css
> +  padding: 2.5rem 10px;
I think it would be better if you use margin-bottom in form and use proper semantics of html tags. 👍 🌈

2023-04-04 14:36 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @MasumaJaffery, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub's review features! 🥇 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 15:10 UTC, merged